import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { unicodeName, unicodeType } from 'unicode-name'

/**
 * The characters to export, as inclusive `[start, end]` code point ranges.
 *
 * Each range is an official Unicode block, sorted ascending and non-overlapping.
 */
const CODE_POINTS: Array<[number, number]> = [
  // Basic Latin
  [0x0020, 0x007E],
  // Latin-1 Supplement
  [0x0080, 0x00FF],
  // General Punctuation
  [0x2000, 0x206F],
  // Miscellaneous Technical
  [0x2300, 0x23FF],
  // Box Drawing
  [0x2500, 0x257F],
  // Block Elements
  [0x2580, 0x259F],
  // Dingbats
  [0x2700, 0x27BF],
  // Miscellaneous Mathematical Symbols-A
  [0x27C0, 0x27EF],
  // The bracket run of CJK Symbols and Punctuation. Not a whole block: the rest
  // of it is kana marks, iteration marks, and CJK-specific punctuation.
  [0x3008, 0x301B],
  // Zero width no-break space. Not a whole block: it is the last code point of
  // Arabic Presentation Forms-B, and we do not want the other 143.
  [0xFEFF, 0xFEFF],
  // Specials
  [0xFFF0, 0xFFFF],
]

/**
 * Only assigned, non-control characters become exports. Everything else
 * (`Control`, `Reserved`, `Noncharacter`, `Surrogate`, `Private-use`) is
 * skipped.
 */
const EXPORTED_TYPES = new Set(['Graphic', 'Format'])

const ROOT_DIR = join(import.meta.dirname, '..')
const INDEX_PATH = join(ROOT_DIR, 'src', 'index.ts')
const README_PATH = join(ROOT_DIR, 'README.md')

const README_START = '<!-- characters:start -->'
const README_END = '<!-- characters:end -->'

const BANNER = '// Generated by scripts/generate.ts. Do not edit.'

interface Character {
  codePoint: number
  name: string
  identifier: string
  escape: string
  /** The literal character, or an empty string when it cannot be shown safely. */
  glyph: string
}

function validateRanges(ranges: Array<[number, number]>): void {
  for (const [index, [start, end]] of ranges.entries()) {
    if (start > end) {
      throw new Error(
        `CODE_POINTS[${index}]: start ${formatCodePoint(start)} is after end ${formatCodePoint(end)}`,
      )
    }
    const next = ranges[index + 1]
    if (next && end >= next[0]) {
      throw new Error(
        `CODE_POINTS[${index}] ends at ${formatCodePoint(end)}, which is not before CODE_POINTS[${index + 1}] starting at ${formatCodePoint(next[0])}`,
      )
    }
  }
}

function formatCodePoint(codePoint: number): string {
  return `U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}`
}

function formatEscape(codePoint: number): string {
  const hex = codePoint.toString(16).toUpperCase()
  return codePoint <= 0xFFFF ? `\\u${hex.padStart(4, '0')}` : `\\u{${hex}}`
}

/**
 * Combining marks latch onto whatever precedes them, and space separators are
 * invisible. Neither survives a trip through a doc comment or a table cell.
 */
function formatGlyph(char: string, type: string): string {
  const printable = type === 'Graphic' && !/\p{M}|\p{Z}/u.test(char)
  return printable ? char : ''
}

function collectCharacters(): Character[] {
  const characters: Character[] = []
  const identifiers = new Map<string, number>()

  for (const [start, end] of CODE_POINTS) {
    for (let codePoint = start; codePoint <= end; codePoint++) {
      const char = String.fromCodePoint(codePoint)
      const type = unicodeType(char)
      if (!type) {
        throw new Error(`codePoint ${codePoint} has no type`)
      }
      if (!EXPORTED_TYPES.has(type)) {
        continue
      }

      const name = unicodeName(codePoint)
      if (!name) {
        throw new Error(`${formatCodePoint(codePoint)} has no name`)
      }

      const identifier = name.replaceAll(/[ -]/g, '_')
      if (!/^[A-Z][A-Z0-9_]*$/.test(identifier)) {
        throw new Error(
          `${formatCodePoint(codePoint)} yields the invalid identifier ${JSON.stringify(identifier)}`,
        )
      }
      const clash = identifiers.get(identifier)
      if (clash != null) {
        throw new Error(
          `${formatCodePoint(codePoint)} and ${formatCodePoint(clash)} both yield the identifier ${identifier}`,
        )
      }
      identifiers.set(identifier, codePoint)

      characters.push({
        codePoint,
        name,
        identifier,
        escape: formatEscape(codePoint),
        glyph: formatGlyph(char, type),
      })
    }
  }

  return characters
}

function renderIndex(characters: Character[]): string {
  const declarations = characters.map((character) => {
    const { name, codePoint, glyph, identifier, escape } = character
    const comment = [name, `(${formatCodePoint(codePoint)})`, glyph].filter(Boolean).join(' ')
    return `/** ${comment} */\nexport const ${identifier} = '${escape}'\n`
  })
  return `${BANNER}\n\n${declarations.join('\n')}`
}

function renderTable(characters: Character[]): string {
  const rows = characters.map(({ identifier, codePoint, glyph }) => {
    return `| \`${identifier}\` | \`${formatCodePoint(codePoint)}\` | ${glyph} |`
  })
  return [
    '| Constant | Code point | Character |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n')
}

function renderReadme(characters: Character[]): string {
  const readme = readFileSync(README_PATH, 'utf8')
  const start = readme.indexOf(README_START)
  const end = readme.indexOf(README_END)
  if (start === -1 || end === -1) {
    throw new Error(`${README_PATH} is missing the ${README_START} / ${README_END} markers`)
  }
  const before = readme.slice(0, start + README_START.length)
  const after = readme.slice(end)
  return `${before}\n\n${renderTable(characters)}\n\n${after}`
}

validateRanges(CODE_POINTS)
const characters = collectCharacters()

// Render both before writing either, so a failure leaves no half-generated file.
const index = renderIndex(characters)
const readme = renderReadme(characters)

writeFileSync(INDEX_PATH, index)
writeFileSync(README_PATH, readme)

console.log(`Generated ${characters.length} characters`)
